// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spweeempthmwxplxumvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwd2VlZW1wdGhtd3hwbHh1bXZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTc4NzAsImV4cCI6MjA2MDIzMzg3MH0.PJ6Xq3nlDjoOZHxogbJrDD_N_7sZH_P0x4JYeTytgUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);